/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.34
 * Generated at: 2025-04-27 21:23:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages.agent;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import model.Utilisateur;

public final class dashboard_005fagent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.0.jar", Long.valueOf(1745494677324L));
    _jspx_dependants.put("jar:file:/C:/Users/User/Desktop/Location_projet/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/LocationMaisons/WEB-INF/lib/jakarta.servlet.jsp.jstl-3.0.0.jar!/META-INF/c-1_2.tld", Long.valueOf(1649428698000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("model.Utilisateur");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "Les JSPs ne permettent que GET, POST ou HEAD. Jasper permet aussi OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

Utilisateur agent = (Utilisateur) session.getAttribute("user");  // ici changé
if (agent == null) {
    response.sendRedirect(request.getContextPath() + "/pages/agent/agent_login.jsp");
    return;
}

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"fr\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <title>Tableau de Bord Agent - Velvet Escape</title>\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap CSS + Font Awesome -->\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css\">\r\n");
      out.write("\r\n");
      out.write("    <style>\r\n");
      out.write("        body {\r\n");
      out.write("            background-color: #f4f6f9;\r\n");
      out.write("        }\r\n");
      out.write("        .navbar-brand {\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            letter-spacing: 1px;\r\n");
      out.write("        }\r\n");
      out.write("        .avatar-circle {\r\n");
      out.write("            width: 40px;\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            background-color: #6c757d;\r\n");
      out.write("            color: white;\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            display: inline-flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            font-weight: bold;\r\n");
      out.write("            text-transform: uppercase;\r\n");
      out.write("        }\r\n");
      out.write("        .card {\r\n");
      out.write("            border-radius: 10px;\r\n");
      out.write("            box-shadow: 0 4px 10px rgba(0, 0, 0, 0.05);\r\n");
      out.write("        }\r\n");
      out.write("        footer {\r\n");
      out.write("            background-color: #343a40;\r\n");
      out.write("            color: #fff;\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar -->\r\n");
      out.write("<nav class=\"navbar navbar-expand-lg navbar-dark bg-dark\">\r\n");
      out.write("    <div class=\"container-fluid\">\r\n");
      out.write("        <a class=\"navbar-brand\" href=\"#\">Agent Panel</a>\r\n");
      out.write("        <div class=\"collapse navbar-collapse justify-content-end\">\r\n");
      out.write("            <ul class=\"navbar-nav align-items-center\">\r\n");
      out.write("                <li class=\"nav-item me-3\">\r\n");
      out.write("                    <div class=\"avatar-circle\" title=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.getPrenom()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.getNom()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                        ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.getPrenom().substring(0,1)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.getNom().substring(0,1)}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                    </div>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item me-3\">\r\n");
      out.write("                    <span class=\"text-white\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.getPrenom()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(' ');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${user.getNom()}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\r\n");
      out.write("                </li>\r\n");
      out.write("                <li class=\"nav-item\">\r\n");
      out.write("                    <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/LogoutServletAgent\">\r\n");
      out.write("                        <i class=\"fas fa-sign-out-alt\"></i> Déconnexion\r\n");
      out.write("                    </a>\r\n");
      out.write("                </li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Main Content -->\r\n");
      out.write("<div class=\"container my-5\">\r\n");
      out.write("    <h2 class=\"text-center mb-4\">Ajouter un Bien</h2>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"card p-4 mb-4\">\r\n");
      out.write("        <form method=\"post\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/AjoutBienServlet\" enctype=\"multipart/form-data\" class=\"row g-3\">\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <select name=\"type\" class=\"form-select\" required>\r\n");
      out.write("                    <option value=\"\">Choisir Type</option>\r\n");
      out.write("                    <option value=\"appartement\">Appartement</option>\r\n");
      out.write("                    <option value=\"house\">Maison</option>\r\n");
      out.write("                    <option value=\"villa luxe\">Villa de Luxe</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <input type=\"number\" step=\"0.01\" name=\"prix_par_jour\" class=\"form-control\" placeholder=\"Prix par jour\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-12\">\r\n");
      out.write("                <textarea name=\"description\" class=\"form-control\" placeholder=\"Description du bien\" rows=\"3\" required></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("                <select name=\"disponibilite\" class=\"form-select\" required>\r\n");
      out.write("                    <option value=\"Disponible\">Disponible</option>\r\n");
      out.write("                    <option value=\"Non Disponible\">Non Disponible</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-md-6\">\r\n");
      out.write("        <!-- Zone Drag & Drop -->\r\n");
      out.write("<div id=\"drop-zone\" class=\"border border-secondary rounded p-5 text-center\" style=\"position: relative;\">\r\n");
      out.write("    <p id=\"drop-text\">Glissez-déposez vos images ici ou cliquez pour choisir</p>\r\n");
      out.write("    <input type=\"file\" name=\"images\" id=\"images\" accept=\"image/*\" multiple style=\"opacity: 0; width: 100%; height: 100%; position: absolute; top: 0; left: 0; cursor: pointer;\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Info Nombre d'Images -->\r\n");
      out.write("<!-- Preview des images -->\r\n");
      out.write("<div id=\"preview-images\" class=\"d-flex flex-wrap mt-3 justify-content-center\"></div>\r\n");
      out.write("\r\n");
      out.write("<!-- Script Drag & Drop -->\r\n");
      out.write("<script>\r\n");
      out.write("    const dropZone = document.getElementById('drop-zone');\r\n");
      out.write("    const inputImages = document.getElementById('images');\r\n");
      out.write("    const previewDiv = document.getElementById('preview-images');\r\n");
      out.write("    const dropText = document.getElementById('drop-text');\r\n");
      out.write("    const imageCount = document.getElementById('image-count');\r\n");
      out.write("\r\n");
      out.write("    let filesList = [];\r\n");
      out.write("\r\n");
      out.write("    // Empêcher comportement défaut\r\n");
      out.write("    ['dragenter', 'dragover', 'dragleave', 'drop'].forEach(eventName => {\r\n");
      out.write("        dropZone.addEventListener(eventName, (e) => e.preventDefault(), false);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    ['dragenter', 'dragover'].forEach(eventName => {\r\n");
      out.write("        dropZone.addEventListener(eventName, () => dropZone.classList.add('bg-light'), false);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    ['dragleave', 'drop'].forEach(eventName => {\r\n");
      out.write("        dropZone.addEventListener(eventName, () => dropZone.classList.remove('bg-light'), false);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    dropZone.addEventListener('drop', (e) => {\r\n");
      out.write("        if (e.dataTransfer.files.length) {\r\n");
      out.write("            filesList = Array.from(e.dataTransfer.files);\r\n");
      out.write("            updateInputFiles();\r\n");
      out.write("            displayPreview();\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    inputImages.addEventListener('change', () => {\r\n");
      out.write("        filesList = Array.from(inputImages.files);\r\n");
      out.write("        displayPreview();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function updateInputFiles() {\r\n");
      out.write("        const dataTransfer = new DataTransfer();\r\n");
      out.write("        filesList.forEach(file => dataTransfer.items.add(file));\r\n");
      out.write("        inputImages.files = dataTransfer.files;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function displayPreview() {\r\n");
      out.write("        previewDiv.innerHTML = \"\";\r\n");
      out.write("        filesList.forEach((file, index) => {\r\n");
      out.write("            const reader = new FileReader();\r\n");
      out.write("            reader.onload = (e) => {\r\n");
      out.write("                const wrapper = document.createElement('div');\r\n");
      out.write("                wrapper.classList.add('position-relative', 'm-2');\r\n");
      out.write("\r\n");
      out.write("                const img = document.createElement('img');\r\n");
      out.write("                img.src = e.target.result;\r\n");
      out.write("                img.classList.add('rounded');\r\n");
      out.write("                img.style.width = '120px';\r\n");
      out.write("                img.style.height = '120px';\r\n");
      out.write("                img.style.objectFit = 'cover';\r\n");
      out.write("                img.style.boxShadow = '0 2px 6px rgba(0,0,0,0.3)';\r\n");
      out.write("\r\n");
      out.write("                const deleteBtn = document.createElement('button');\r\n");
      out.write("                deleteBtn.innerHTML = '❌';\r\n");
      out.write("                deleteBtn.classList.add('btn', 'btn-sm', 'btn-danger', 'position-absolute');\r\n");
      out.write("                deleteBtn.style.top = '5px';\r\n");
      out.write("                deleteBtn.style.right = '5px';\r\n");
      out.write("                deleteBtn.style.padding = '2px 6px';\r\n");
      out.write("                deleteBtn.onclick = () => {\r\n");
      out.write("                    filesList.splice(index, 1);\r\n");
      out.write("                    updateInputFiles();\r\n");
      out.write("                    displayPreview();\r\n");
      out.write("                };\r\n");
      out.write("\r\n");
      out.write("                wrapper.appendChild(img);\r\n");
      out.write("                wrapper.appendChild(deleteBtn);\r\n");
      out.write("                previewDiv.appendChild(wrapper);\r\n");
      out.write("            };\r\n");
      out.write("            reader.readAsDataURL(file);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("    #drop-zone {\r\n");
      out.write("        border: 2px dashed #ced4da;\r\n");
      out.write("        background-color: #f8f9fa;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: background-color 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("    #drop-zone:hover {\r\n");
      out.write("        background-color: #e2e6ea;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                \r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-12 text-end\">\r\n");
      out.write("                <button type=\"submit\" class=\"btn btn-primary\">\r\n");
      out.write("                    <i class=\"fas fa-plus\"></i> Ajouter le Bien\r\n");
      out.write("                </button>\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Nouveau bouton Mes Biens -->\r\n");
      out.write("    <div class=\"text-center\">\r\n");
      out.write("        <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (jakarta.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/ListeBiensServlet\" class=\"btn btn-outline-secondary\">\r\n");
      out.write("            <i class=\"fas fa-list\"></i> Mes Biens\r\n");
      out.write("        </a>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Footer -->\r\n");
      out.write("<footer class=\"text-center py-4 mt-5\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        &copy; 2025 Velvet Escape - Tous droits réservés\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
